### PR TITLE
feat: active developer flag

### PR DESCRIPTION
**Pull request by PuffinDevelopment**
This will recognize discord active developers.

### CODE REVIEW

**Comment by almostSouji** [comment]
that probably also needs a dependency update then? last one was before the badge was released in DJs afaik

**Comment by puffinnnnn** [comment]
yep, `discord.js` must be updated to `^14.7.0` in order for this to work

**Comment by almostSouji** [comment]
so this PR needs to include the package and lockfile changes

**Comment by puffinnnnn** [comment]
@almostSouji, I have updated the PR

**Review by JPBM135 — APPROVED** [review]
Tested!

**Pull request merged**
